
package com.unblu.webapi.model.v4;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * AnalyticsKpiReferenceLineTranslation
 */

@JsonPropertyOrder({
	AnalyticsKpiReferenceLineTranslation.JSON_PROPERTY_$_TYPE,
	AnalyticsKpiReferenceLineTranslation.JSON_PROPERTY_ID,
	AnalyticsKpiReferenceLineTranslation.JSON_PROPERTY_LABEL,
})
@JsonAutoDetect(creatorVisibility = Visibility.NONE, fieldVisibility = Visibility.NONE, getterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
public class AnalyticsKpiReferenceLineTranslation {
	/**
	 * Gets or Sets $type
	 */
	public enum TypeEnum {
		ANALYTICSKPIREFERENCELINETRANSLATION("AnalyticsKpiReferenceLineTranslation");

		private String value;

		TypeEnum(String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		@JsonCreator
		public static TypeEnum fromValue(String value) {
			for (TypeEnum b : TypeEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			return TypeEnum.ANALYTICSKPIREFERENCELINETRANSLATION;
		}
	}

	public static final String JSON_PROPERTY_$_TYPE = "$_type";
	@JsonProperty(JSON_PROPERTY_$_TYPE)
	private TypeEnum $type = TypeEnum.ANALYTICSKPIREFERENCELINETRANSLATION;

	public static final String JSON_PROPERTY_ID = "id";
	@JsonProperty(JSON_PROPERTY_ID)
	private String id;

	public static final String JSON_PROPERTY_LABEL = "label";
	@JsonProperty(JSON_PROPERTY_LABEL)
	private String label;

	public AnalyticsKpiReferenceLineTranslation $type(TypeEnum $type) {
		this.$type = $type;
		return this;
	}

	/**
	 * Get $type
	 * 
	 * @return $type
	 **/
	@ApiModelProperty(value = "")
	public TypeEnum get$Type() {
		return $type;
	}

	public void set$Type(TypeEnum $type) {
		this.$type = $type;
	}

	public AnalyticsKpiReferenceLineTranslation id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Unique ID of the entity. When creating an entity this property can be omitted; it is generated by the server.
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "Unique ID of the entity. When creating an entity this property can be omitted; it is generated by the server.")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public AnalyticsKpiReferenceLineTranslation label(String label) {
		this.label = label;
		return this;
	}

	/**
	 * Translated label of the entity this translation entity belongs to.
	 * 
	 * @return label
	 **/
	@ApiModelProperty(value = "Translated label of the entity this translation entity belongs to.")
	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AnalyticsKpiReferenceLineTranslation analyticsKpiReferenceLineTranslation = (AnalyticsKpiReferenceLineTranslation) o;
		return Objects.equals(this.$type, analyticsKpiReferenceLineTranslation.$type) &&
				Objects.equals(this.id, analyticsKpiReferenceLineTranslation.id) &&
				Objects.equals(this.label, analyticsKpiReferenceLineTranslation.label);
	}

	@Override
	public int hashCode() {
		return Objects.hash($type, id, label);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AnalyticsKpiReferenceLineTranslation {\n");
		sb.append("    $type: ").append(toIndentedString($type)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    label: ").append(toIndentedString(label)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
