
package com.unblu.webapi.model.v4;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * CustomChannelContactIdentifierTranslation
 */

@JsonPropertyOrder({
	CustomChannelContactIdentifierTranslation.JSON_PROPERTY_$_TYPE,
	CustomChannelContactIdentifierTranslation.JSON_PROPERTY_ID,
	CustomChannelContactIdentifierTranslation.JSON_PROPERTY_NAME,
})
@JsonAutoDetect(creatorVisibility = Visibility.NONE, fieldVisibility = Visibility.NONE, getterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
public class CustomChannelContactIdentifierTranslation {
	/**
	 * Gets or Sets $type
	 */
	public enum TypeEnum {
		CUSTOMCHANNELCONTACTIDENTIFIERTRANSLATION("CustomChannelContactIdentifierTranslation");

		private String value;

		TypeEnum(String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		@JsonCreator
		public static TypeEnum fromValue(String value) {
			for (TypeEnum b : TypeEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			return TypeEnum.CUSTOMCHANNELCONTACTIDENTIFIERTRANSLATION;
		}
	}

	public static final String JSON_PROPERTY_$_TYPE = "$_type";
	@JsonProperty(JSON_PROPERTY_$_TYPE)
	private TypeEnum $type = TypeEnum.CUSTOMCHANNELCONTACTIDENTIFIERTRANSLATION;

	public static final String JSON_PROPERTY_ID = "id";
	@JsonProperty(JSON_PROPERTY_ID)
	private String id;

	public static final String JSON_PROPERTY_NAME = "name";
	@JsonProperty(JSON_PROPERTY_NAME)
	private String name;

	public CustomChannelContactIdentifierTranslation $type(TypeEnum $type) {
		this.$type = $type;
		return this;
	}

	/**
	 * Get $type
	 * 
	 * @return $type
	 **/
	@ApiModelProperty(value = "")
	public TypeEnum get$Type() {
		return $type;
	}

	public void set$Type(TypeEnum $type) {
		this.$type = $type;
	}

	public CustomChannelContactIdentifierTranslation id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Unique ID of the entity. When creating an entity this property can be omitted; it is generated by the server.
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "Unique ID of the entity. When creating an entity this property can be omitted; it is generated by the server.")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public CustomChannelContactIdentifierTranslation name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Translated name of the entity this translation entity belongs to
	 * 
	 * @return name
	 **/
	@ApiModelProperty(value = "Translated name of the entity this translation entity belongs to")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CustomChannelContactIdentifierTranslation customChannelContactIdentifierTranslation = (CustomChannelContactIdentifierTranslation) o;
		return Objects.equals(this.$type, customChannelContactIdentifierTranslation.$type) &&
				Objects.equals(this.id, customChannelContactIdentifierTranslation.id) &&
				Objects.equals(this.name, customChannelContactIdentifierTranslation.name);
	}

	@Override
	public int hashCode() {
		return Objects.hash($type, id, name);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CustomChannelContactIdentifierTranslation {\n");
		sb.append("    $type: ").append(toIndentedString($type)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
