
package com.unblu.webapi.model.v4;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Model of dictionary. Dictionaries contain words for spell checking purposes.
 */
@ApiModel(description = "Model of dictionary. Dictionaries contain words for spell checking purposes.")

@JsonPropertyOrder({
	DictionaryEntry.JSON_PROPERTY_$_TYPE,
	DictionaryEntry.JSON_PROPERTY_ID,
	DictionaryEntry.JSON_PROPERTY_CREATION_TIMESTAMP,
	DictionaryEntry.JSON_PROPERTY_MODIFICATION_TIMESTAMP,
	DictionaryEntry.JSON_PROPERTY_VERSION,
	DictionaryEntry.JSON_PROPERTY_ACCOUNT_ID,
	DictionaryEntry.JSON_PROPERTY_OWNER_ID,
	DictionaryEntry.JSON_PROPERTY_OWNER_TYPE,
	DictionaryEntry.JSON_PROPERTY_WORD,
	DictionaryEntry.JSON_PROPERTY_LANGUAGE,
})
@JsonAutoDetect(creatorVisibility = Visibility.NONE, fieldVisibility = Visibility.NONE, getterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
public class DictionaryEntry {
	/**
	 * Gets or Sets $type
	 */
	public enum TypeEnum {
		DICTIONARYENTRY("DictionaryEntry");

		private String value;

		TypeEnum(String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		@JsonCreator
		public static TypeEnum fromValue(String value) {
			for (TypeEnum b : TypeEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			return TypeEnum.DICTIONARYENTRY;
		}
	}

	public static final String JSON_PROPERTY_$_TYPE = "$_type";
	@JsonProperty(JSON_PROPERTY_$_TYPE)
	private TypeEnum $type = TypeEnum.DICTIONARYENTRY;

	public static final String JSON_PROPERTY_ID = "id";
	@JsonProperty(JSON_PROPERTY_ID)
	private String id;

	public static final String JSON_PROPERTY_CREATION_TIMESTAMP = "creationTimestamp";
	@JsonProperty(JSON_PROPERTY_CREATION_TIMESTAMP)
	private Long creationTimestamp;

	public static final String JSON_PROPERTY_MODIFICATION_TIMESTAMP = "modificationTimestamp";
	@JsonProperty(JSON_PROPERTY_MODIFICATION_TIMESTAMP)
	private Long modificationTimestamp;

	public static final String JSON_PROPERTY_VERSION = "version";
	@JsonProperty(JSON_PROPERTY_VERSION)
	private Long version;

	public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
	@JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
	private String accountId;

	public static final String JSON_PROPERTY_OWNER_ID = "ownerId";
	@JsonProperty(JSON_PROPERTY_OWNER_ID)
	private String ownerId;

	public static final String JSON_PROPERTY_OWNER_TYPE = "ownerType";
	@JsonProperty(JSON_PROPERTY_OWNER_TYPE)
	private EPropertyOwnerType ownerType;

	public static final String JSON_PROPERTY_WORD = "word";
	@JsonProperty(JSON_PROPERTY_WORD)
	private String word;

	public static final String JSON_PROPERTY_LANGUAGE = "language";
	@JsonProperty(JSON_PROPERTY_LANGUAGE)
	private String language;

	public DictionaryEntry $type(TypeEnum $type) {
		this.$type = $type;
		return this;
	}

	/**
	 * Get $type
	 * 
	 * @return $type
	 **/
	@ApiModelProperty(value = "")
	public TypeEnum get$Type() {
		return $type;
	}

	public void set$Type(TypeEnum $type) {
		this.$type = $type;
	}

	public DictionaryEntry id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Unique ID of the entity. When creating an entity, this property can be omitted; it&#39;s generated by the server.
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "Unique ID of the entity. When creating an entity, this property can be omitted; it's generated by the server.")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public DictionaryEntry creationTimestamp(Long creationTimestamp) {
		this.creationTimestamp = creationTimestamp;
		return this;
	}

	/**
	 * Creation timestamp of the entity. It is defined when the entity is first stored in Unblu. Any value sent to the Unblu server is ignored, so it can be
	 * omitted. Note: If you set this property, Unblu returns the same value, but it isn&#39;t written to storage and doesn&#39;t affect data consistency.
	 * 
	 * @return creationTimestamp
	 **/
	@ApiModelProperty(value = "Creation timestamp of the entity. It is defined when the entity is first stored in Unblu. Any value sent to the Unblu server is ignored, so it can be omitted. Note: If you set this property, Unblu returns the same value, but it isn't written to storage and doesn't affect data consistency.")
	public Long getCreationTimestamp() {
		return creationTimestamp;
	}

	public void setCreationTimestamp(Long creationTimestamp) {
		this.creationTimestamp = creationTimestamp;
	}

	public DictionaryEntry modificationTimestamp(Long modificationTimestamp) {
		this.modificationTimestamp = modificationTimestamp;
		return this;
	}

	/**
	 * Timestamp of the last modification. This property is always optional and can be omitted when sending data to the server. If sent to the server, it is
	 * ignored. It is only informational in character. Note: If you set this property, it returns the same value but it isn&#39;t written to storage and doesn&#39;t
	 * affect the data consistency.
	 * 
	 * @return modificationTimestamp
	 **/
	@ApiModelProperty(value = "Timestamp of the last modification. This property is always optional and can be omitted when sending data to the server. If sent to the server, it is ignored. It is only informational in character. Note: If you set this property, it returns the same value but it isn't written to storage and doesn't affect the data consistency.")
	public Long getModificationTimestamp() {
		return modificationTimestamp;
	}

	public void setModificationTimestamp(Long modificationTimestamp) {
		this.modificationTimestamp = modificationTimestamp;
	}

	public DictionaryEntry version(Long version) {
		this.version = version;
		return this;
	}

	/**
	 * Version of the entity. Will be incremented on each change. New updates must always be based on the newest version, if not updates will be rejected. When
	 * creating an object, the version can be omitted.
	 * 
	 * @return version
	 **/
	@ApiModelProperty(value = "Version of the entity. Will be incremented on each change. New updates must always be based on the newest version, if not updates will be rejected. When creating an object, the version can be omitted.")
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public DictionaryEntry accountId(String accountId) {
		this.accountId = accountId;
		return this;
	}

	/**
	 * ID of the account the entity belongs to. When creating an entity, the account ID can be omitted. It will be filled by the server with the account ID of the
	 * user currently logged in. When editing an entity, you must include the account ID.
	 * 
	 * @return accountId
	 **/
	@ApiModelProperty(value = "ID of the account the entity belongs to. When creating an entity, the account ID can be omitted. It will be filled by the server with the account ID of the user currently logged in. When editing an entity, you must include the account ID.")
	public String getAccountId() {
		return accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public DictionaryEntry ownerId(String ownerId) {
		this.ownerId = ownerId;
		return this;
	}

	/**
	 * Id of the owner of the entity. Can not be omitted.
	 * 
	 * @return ownerId
	 **/
	@ApiModelProperty(value = "Id of the owner of the entity. Can not be omitted.")
	public String getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}

	public DictionaryEntry ownerType(EPropertyOwnerType ownerType) {
		this.ownerType = ownerType;
		return this;
	}

	/**
	 * Get ownerType
	 * 
	 * @return ownerType
	 **/
	@ApiModelProperty(value = "")
	public EPropertyOwnerType getOwnerType() {
		return ownerType;
	}

	public void setOwnerType(EPropertyOwnerType ownerType) {
		this.ownerType = ownerType;
	}

	public DictionaryEntry word(String word) {
		this.word = word;
		return this;
	}

	/**
	 * The word stored in the dictionary. Maximum of 100 characters.
	 * 
	 * @return word
	 **/
	@ApiModelProperty(value = "The word stored in the dictionary. Maximum of 100 characters.")
	public String getWord() {
		return word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	public DictionaryEntry language(String language) {
		this.language = language;
		return this;
	}

	/**
	 * &lt;p&gt; Only dictionary words without a language or matching a conversation&#39;s language are used for spell checking.&lt;br&gt; The following rules
	 * apply: &lt;ul&gt; &lt;li&gt;Dictionary words with no language defined are used for all conversations.&lt;/li&gt; &lt;li&gt;If the conversation language (e.g.
	 * \&quot;en-us\&quot;) is more specific than the language of the dictionary word (e.g. \&quot;en\&quot;), the dictionary word is also used.&lt;/li&gt;
	 * &lt;li&gt;If the language of the dictionary word (e.g. \&quot;en-us\&quot;) is &lt;i&gt;more&lt;/i&gt; specific than the conversation language (e.g.
	 * \&quot;en\&quot;), the dictionary word &lt;b&gt;isn&#39;t&lt;/b&gt; used.&lt;/li&gt;
	 * 
	 * @return language
	 **/
	@ApiModelProperty(value = "<p> Only dictionary words without a language or matching a conversation's language are used for spell checking.<br> The following rules apply: <ul> <li>Dictionary words with no language defined are used for all conversations.</li> <li>If the conversation language (e.g. \"en-us\") is more specific than the language of the dictionary word (e.g. \"en\"), the dictionary word is also used.</li> <li>If the language of the dictionary word (e.g. \"en-us\") is <i>more</i> specific than the conversation language (e.g. \"en\"), the dictionary word <b>isn't</b> used.</li>")
	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		DictionaryEntry dictionaryEntry = (DictionaryEntry) o;
		return Objects.equals(this.$type, dictionaryEntry.$type) &&
				Objects.equals(this.id, dictionaryEntry.id) &&
				Objects.equals(this.creationTimestamp, dictionaryEntry.creationTimestamp) &&
				Objects.equals(this.modificationTimestamp, dictionaryEntry.modificationTimestamp) &&
				Objects.equals(this.version, dictionaryEntry.version) &&
				Objects.equals(this.accountId, dictionaryEntry.accountId) &&
				Objects.equals(this.ownerId, dictionaryEntry.ownerId) &&
				Objects.equals(this.ownerType, dictionaryEntry.ownerType) &&
				Objects.equals(this.word, dictionaryEntry.word) &&
				Objects.equals(this.language, dictionaryEntry.language);
	}

	@Override
	public int hashCode() {
		return Objects.hash($type, id, creationTimestamp, modificationTimestamp, version, accountId, ownerId, ownerType, word, language);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class DictionaryEntry {\n");
		sb.append("    $type: ").append(toIndentedString($type)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
		sb.append("    modificationTimestamp: ").append(toIndentedString(modificationTimestamp)).append("\n");
		sb.append("    version: ").append(toIndentedString(version)).append("\n");
		sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
		sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
		sb.append("    ownerType: ").append(toIndentedString(ownerType)).append("\n");
		sb.append("    word: ").append(toIndentedString(word)).append("\n");
		sb.append("    language: ").append(toIndentedString(language)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
