
package com.unblu.webapi.model.v4;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Dictionary model class for spell checking
 */
@ApiModel(description = "Dictionary model class for spell checking")

@JsonPropertyOrder({
	DictionaryData.JSON_PROPERTY_$_TYPE,
	DictionaryData.JSON_PROPERTY_ID,
	DictionaryData.JSON_PROPERTY_CREATION_TIMESTAMP,
	DictionaryData.JSON_PROPERTY_MODIFICATION_TIMESTAMP,
	DictionaryData.JSON_PROPERTY_VERSION,
	DictionaryData.JSON_PROPERTY_ACCOUNT_ID,
	DictionaryData.JSON_PROPERTY_TYPE,
	DictionaryData.JSON_PROPERTY_LANGUAGE,
	DictionaryData.JSON_PROPERTY_AFF_FILE,
	DictionaryData.JSON_PROPERTY_DIC_FILE,
})
@JsonAutoDetect(creatorVisibility = Visibility.NONE, fieldVisibility = Visibility.NONE, getterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
public class DictionaryData {
	/**
	 * Gets or Sets $type
	 */
	public enum TypeEnum {
		DICTIONARYDATA("DictionaryData");

		private String value;

		TypeEnum(String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		@JsonCreator
		public static TypeEnum fromValue(String value) {
			for (TypeEnum b : TypeEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			return TypeEnum.DICTIONARYDATA;
		}
	}

	public static final String JSON_PROPERTY_$_TYPE = "$_type";
	@JsonProperty(JSON_PROPERTY_$_TYPE)
	private TypeEnum $type = TypeEnum.DICTIONARYDATA;

	public static final String JSON_PROPERTY_ID = "id";
	@JsonProperty(JSON_PROPERTY_ID)
	private String id;

	public static final String JSON_PROPERTY_CREATION_TIMESTAMP = "creationTimestamp";
	@JsonProperty(JSON_PROPERTY_CREATION_TIMESTAMP)
	private Long creationTimestamp;

	public static final String JSON_PROPERTY_MODIFICATION_TIMESTAMP = "modificationTimestamp";
	@JsonProperty(JSON_PROPERTY_MODIFICATION_TIMESTAMP)
	private Long modificationTimestamp;

	public static final String JSON_PROPERTY_VERSION = "version";
	@JsonProperty(JSON_PROPERTY_VERSION)
	private Long version;

	public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
	@JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
	private String accountId;

	public static final String JSON_PROPERTY_TYPE = "type";
	@JsonProperty(JSON_PROPERTY_TYPE)
	private EDictionaryType type;

	public static final String JSON_PROPERTY_LANGUAGE = "language";
	@JsonProperty(JSON_PROPERTY_LANGUAGE)
	private String language;

	public static final String JSON_PROPERTY_AFF_FILE = "affFile";
	@JsonProperty(JSON_PROPERTY_AFF_FILE)
	private ExpandableField<DictionaryFileContent> affFile = null;

	public static final String JSON_PROPERTY_DIC_FILE = "dicFile";
	@JsonProperty(JSON_PROPERTY_DIC_FILE)
	private ExpandableField<DictionaryFileContent> dicFile = null;

	public DictionaryData $type(TypeEnum $type) {
		this.$type = $type;
		return this;
	}

	/**
	 * Get $type
	 * 
	 * @return $type
	 **/
	@ApiModelProperty(value = "")
	public TypeEnum get$Type() {
		return $type;
	}

	public void set$Type(TypeEnum $type) {
		this.$type = $type;
	}

	public DictionaryData id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Unique ID of the entity. When creating an entity, this property can be omitted; it&#39;s generated by the server.
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "Unique ID of the entity. When creating an entity, this property can be omitted; it's generated by the server.")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public DictionaryData creationTimestamp(Long creationTimestamp) {
		this.creationTimestamp = creationTimestamp;
		return this;
	}

	/**
	 * Creation timestamp of the entity. It is defined when the entity is first stored in Unblu. Any value sent to the Unblu server is ignored, so it can be
	 * omitted. Note: If you set this property, Unblu returns the same value, but it isn&#39;t written to storage and doesn&#39;t affect data consistency.
	 * 
	 * @return creationTimestamp
	 **/
	@ApiModelProperty(value = "Creation timestamp of the entity. It is defined when the entity is first stored in Unblu. Any value sent to the Unblu server is ignored, so it can be omitted. Note: If you set this property, Unblu returns the same value, but it isn't written to storage and doesn't affect data consistency.")
	public Long getCreationTimestamp() {
		return creationTimestamp;
	}

	public void setCreationTimestamp(Long creationTimestamp) {
		this.creationTimestamp = creationTimestamp;
	}

	public DictionaryData modificationTimestamp(Long modificationTimestamp) {
		this.modificationTimestamp = modificationTimestamp;
		return this;
	}

	/**
	 * Timestamp of the last modification. This property is always optional and can be omitted when sending data to the server. If sent to the server, it is
	 * ignored. It is only informational in character. Note: If you set this property, it returns the same value but it isn&#39;t written to storage and doesn&#39;t
	 * affect the data consistency.
	 * 
	 * @return modificationTimestamp
	 **/
	@ApiModelProperty(value = "Timestamp of the last modification. This property is always optional and can be omitted when sending data to the server. If sent to the server, it is ignored. It is only informational in character. Note: If you set this property, it returns the same value but it isn't written to storage and doesn't affect the data consistency.")
	public Long getModificationTimestamp() {
		return modificationTimestamp;
	}

	public void setModificationTimestamp(Long modificationTimestamp) {
		this.modificationTimestamp = modificationTimestamp;
	}

	public DictionaryData version(Long version) {
		this.version = version;
		return this;
	}

	/**
	 * Version of the entity. Will be incremented on each change. New updates must always be based on the newest version, if not updates will be rejected. When
	 * creating an object, the version can be omitted.
	 * 
	 * @return version
	 **/
	@ApiModelProperty(value = "Version of the entity. Will be incremented on each change. New updates must always be based on the newest version, if not updates will be rejected. When creating an object, the version can be omitted.")
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public DictionaryData accountId(String accountId) {
		this.accountId = accountId;
		return this;
	}

	/**
	 * ID of the account the entity belongs to. When creating an entity, the account ID can be omitted. It will be filled by the server with the account ID of the
	 * user currently logged in. When editing an entity, you must include the account ID.
	 * 
	 * @return accountId
	 **/
	@ApiModelProperty(value = "ID of the account the entity belongs to. When creating an entity, the account ID can be omitted. It will be filled by the server with the account ID of the user currently logged in. When editing an entity, you must include the account ID.")
	public String getAccountId() {
		return accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public DictionaryData type(EDictionaryType type) {
		this.type = type;
		return this;
	}

	/**
	 * Get type
	 * 
	 * @return type
	 **/
	@ApiModelProperty(value = "")
	public EDictionaryType getType() {
		return type;
	}

	public void setType(EDictionaryType type) {
		this.type = type;
	}

	public DictionaryData language(String language) {
		this.language = language;
		return this;
	}

	/**
	 * Language of the dictionary (e.g., \&quot;en\&quot;, \&quot;de\&quot;, \&quot;fr\&quot;)
	 * 
	 * @return language
	 **/
	@ApiModelProperty(value = "Language of the dictionary (e.g., \"en\", \"de\", \"fr\")")
	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public DictionaryData affFile(ExpandableField<DictionaryFileContent> affFile) {
		this.affFile = affFile;
		return this;
	}

	/**
	 * AFF file of the entity: ID that can be expanded.
	 * 
	 * @return affFile
	 **/
	@ApiModelProperty(value = "AFF file of the entity: ID that can be expanded.")
	public ExpandableField<DictionaryFileContent> getAffFile() {
		return affFile;
	}

	public void setAffFile(ExpandableField<DictionaryFileContent> affFile) {
		this.affFile = affFile;
	}

	public DictionaryData dicFile(ExpandableField<DictionaryFileContent> dicFile) {
		this.dicFile = dicFile;
		return this;
	}

	/**
	 * DIC file of the entity: ID that can be expanded.
	 * 
	 * @return dicFile
	 **/
	@ApiModelProperty(value = "DIC file of the entity: ID that can be expanded.")
	public ExpandableField<DictionaryFileContent> getDicFile() {
		return dicFile;
	}

	public void setDicFile(ExpandableField<DictionaryFileContent> dicFile) {
		this.dicFile = dicFile;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		DictionaryData dictionaryData = (DictionaryData) o;
		return Objects.equals(this.$type, dictionaryData.$type) &&
				Objects.equals(this.id, dictionaryData.id) &&
				Objects.equals(this.creationTimestamp, dictionaryData.creationTimestamp) &&
				Objects.equals(this.modificationTimestamp, dictionaryData.modificationTimestamp) &&
				Objects.equals(this.version, dictionaryData.version) &&
				Objects.equals(this.accountId, dictionaryData.accountId) &&
				Objects.equals(this.type, dictionaryData.type) &&
				Objects.equals(this.language, dictionaryData.language) &&
				Objects.equals(this.affFile, dictionaryData.affFile) &&
				Objects.equals(this.dicFile, dictionaryData.dicFile);
	}

	@Override
	public int hashCode() {
		return Objects.hash($type, id, creationTimestamp, modificationTimestamp, version, accountId, type, language, affFile, dicFile);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class DictionaryData {\n");
		sb.append("    $type: ").append(toIndentedString($type)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
		sb.append("    modificationTimestamp: ").append(toIndentedString(modificationTimestamp)).append("\n");
		sb.append("    version: ").append(toIndentedString(version)).append("\n");
		sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("    language: ").append(toIndentedString(language)).append("\n");
		sb.append("    affFile: ").append(toIndentedString(affFile)).append("\n");
		sb.append("    dicFile: ").append(toIndentedString(dicFile)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
