
package com.unblu.webapi.model.v4;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The message type of a conversation message
 */
public enum EMessageType {

	/**
	 * TEXT: A plain text message written by a participant
	 */
	TEXT("TEXT"),

	/**
	 * SYSTEM: A message generated by the system to report an event in the conversation
	 */
	SYSTEM("SYSTEM"),

	/**
	 * FILE: A message carrying an uploaded file
	 */
	FILE("FILE"),

	/**
	 * CARD: A message rendered as a card with a title, an image, and actions
	 */
	CARD("CARD"),

	/**
	 * LIST: A message rendered as a list of items, each of which may carry an action
	 */
	LIST("LIST"),

	/**
	 * APPROVAL_REQUEST: A question asking the recipient to approve or reject something
	 */
	APPROVAL_REQUEST("APPROVAL_REQUEST"),

	/**
	 * MULTICHOICE_QUESTION: A question offering the recipient a set of answers to choose from
	 */
	MULTICHOICE_QUESTION("MULTICHOICE_QUESTION"),

	/**
	 * RATING_QUESTION: A question asking the recipient for a rating
	 */
	RATING_QUESTION("RATING_QUESTION"),

	/**
	 * TEXT_QUESTION: A question asking the recipient for a free-text answer
	 */
	TEXT_QUESTION("TEXT_QUESTION"),

	/**
	 * REPLY: The answer a participant gave to a question message
	 */
	REPLY("REPLY"),

	/**
	 * QUESTION_ABORTED: A message reporting that a question was canceled before it was answered
	 */
	QUESTION_ABORTED("QUESTION_ABORTED"),

	/**
	 * RECORDING_AVAILABLE: A message announcing that a conversation recording is ready
	 */
	RECORDING_AVAILABLE("RECORDING_AVAILABLE"),

	/**
	 * WHATS_APP_TEMPLATE: A message sent as a pre-approved WhatsApp message template
	 */
	WHATS_APP_TEMPLATE("WHATS_APP_TEMPLATE");

	private String value;

	EMessageType(String value) {
		this.value = value;
	}

	@JsonValue
	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return String.valueOf(value);
	}

	@JsonCreator
	public static EMessageType fromValue(String value) {
		for (EMessageType b : EMessageType.values()) {
			if (b.value.equals(value)) {
				return b;
			}
		}
		throw new IllegalArgumentException("Unexpected value '" + value + "'");
	}
}
