
package com.unblu.webapi.model.v4;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * InternalMessageInterceptorTranslation
 */

@JsonPropertyOrder({
	InternalMessageInterceptorTranslation.JSON_PROPERTY_$_TYPE,
	InternalMessageInterceptorTranslation.JSON_PROPERTY_ID,
	InternalMessageInterceptorTranslation.JSON_PROPERTY_REASON,
})
@JsonAutoDetect(creatorVisibility = Visibility.NONE, fieldVisibility = Visibility.NONE, getterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
public class InternalMessageInterceptorTranslation {
	/**
	 * Gets or Sets $type
	 */
	public enum TypeEnum {
		INTERNALMESSAGEINTERCEPTORTRANSLATION("InternalMessageInterceptorTranslation");

		private String value;

		TypeEnum(String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		@JsonCreator
		public static TypeEnum fromValue(String value) {
			for (TypeEnum b : TypeEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			return TypeEnum.INTERNALMESSAGEINTERCEPTORTRANSLATION;
		}
	}

	public static final String JSON_PROPERTY_$_TYPE = "$_type";
	@JsonProperty(JSON_PROPERTY_$_TYPE)
	private TypeEnum $type = TypeEnum.INTERNALMESSAGEINTERCEPTORTRANSLATION;

	public static final String JSON_PROPERTY_ID = "id";
	@JsonProperty(JSON_PROPERTY_ID)
	private String id;

	public static final String JSON_PROPERTY_REASON = "reason";
	@JsonProperty(JSON_PROPERTY_REASON)
	private String reason;

	public InternalMessageInterceptorTranslation $type(TypeEnum $type) {
		this.$type = $type;
		return this;
	}

	/**
	 * Get $type
	 * 
	 * @return $type
	 **/
	@ApiModelProperty(value = "")
	public TypeEnum get$Type() {
		return $type;
	}

	public void set$Type(TypeEnum $type) {
		this.$type = $type;
	}

	public InternalMessageInterceptorTranslation id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Unique ID of the entity. When creating an entity, this property can be omitted, the ID is generated by the server.
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "Unique ID of the entity. When creating an entity, this property can be omitted, the ID is generated by the server.")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public InternalMessageInterceptorTranslation reason(String reason) {
		this.reason = reason;
		return this;
	}

	/**
	 * The reason shown when a message is rejected. If a translation of the reason exists in the language of the conversation, it&#39;s used. Otherwise this value
	 * is used.
	 * 
	 * @return reason
	 **/
	@ApiModelProperty(value = "The reason shown when a message is rejected. If a translation of the reason exists in the language of the conversation, it's used. Otherwise this value is used.")
	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		InternalMessageInterceptorTranslation internalMessageInterceptorTranslation = (InternalMessageInterceptorTranslation) o;
		return Objects.equals(this.$type, internalMessageInterceptorTranslation.$type) &&
				Objects.equals(this.id, internalMessageInterceptorTranslation.id) &&
				Objects.equals(this.reason, internalMessageInterceptorTranslation.reason);
	}

	@Override
	public int hashCode() {
		return Objects.hash($type, id, reason);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class InternalMessageInterceptorTranslation {\n");
		sb.append("    $type: ").append(toIndentedString($type)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
