plugins {
    id 'org.jreleaser' version '1.19.0'
    id 'net.researchgate.release' version '3.1.0'
}

wrapper {
    gradleVersion = '7.6.6'
}

String groupId = 'com.unblu.openapi'
group = groupId

subprojects {
    apply plugin: 'java'
    apply plugin: 'signing'
    apply plugin: 'maven-publish'

    group = groupId

    java {
        withJavadocJar()
        withSourcesJar()

        compileJava.options.encoding = "UTF-8"
        toolchain {
            languageVersion = JavaLanguageVersion.of(8)
        }
    }

    repositories {
        mavenCentral()
    }

    publishing {
        repositories {
            maven {
                url = rootProject.file('build/staging-deploy')
            }
        }
    }
}

jreleaser {
    signing {
        active = 'RELEASE'
        armored = true
    }
    deploy {
        maven {
            mavenCentral {
                unblu {
                    active = 'RELEASE'
                    namespace = 'com.unblu'
                    url = 'https://central.sonatype.com/api/v1/publisher'
                    stagingRepository('build/staging-deploy')
                    retryDelay = 30
                    maxRetries = 150
                }
            }
        }
    }
    release {
        github {
            enabled = true
            repoOwner = "$githubRepositoryOwner"
            name = "$githubRepositoryName"
            tagName = '{{projectVersion}}'
            overwrite = true
            skipTag = true
            makeLatest = 'legacy'
            releaseNotes {
                enabled = true
            }
            changelog {
                enabled = false
            }
        }
    }
}

release {
    buildTasks = [
        'checkLastVersionValue',
        'publish',
        'jreleaserDeploy',
        'clean',
        'build'
    ]
    git {
        requireBranch.set('main/6.x.x')
    }
}

tasks.register('checkLastVersionValue') {
    doLast {
        if(version.endsWith('SNAPSHOT')) {
            throw new GradleException("version '$version' ends with SNAPSHOT, this is not a release build!")
        }
        if(lastVersion != version) {
            throw new GradleException("lastVersion '$lastVersion' does not match version '$version', fix it in the 'gradle.properties' file.")
        }
    }
}

def updateLastVersionValueTask = tasks.register('updateLastVersionValue') {
    doLast {
        def propertiesFile = file('gradle.properties')
        def content = propertiesFile.text
        def newVersion = project.findProperty('release.releaseVersion') ?: version.replace('-SNAPSHOT', '')
        content = content.replaceAll("lastVersion=[0-9a-z\\.\\-]+", "lastVersion=" + newVersion)
        propertiesFile.text = content
    }
}

model {
    tasks.unSnapshotVersion {
        dependsOn updateLastVersionValueTask
    }
}
